### ISSUE TITLE
The corresponding header file in the ADP8866 library

### ISSUE THREAD

**Issue by 13970252381** [jspark311/ADP8866-Breakout#1]
Hello, when I was using this library, I found that I could not find the corresponding library of the following four header files. Could you please provide it to me?thank you
# include <inttypes.h>
# include <stdint.h>
# include <Kernel.h>
# include "Platform/Peripherals/I2C/I2CAdapter. h"

**Comment by jspark311** [comment]
This driver has not been ported. What you see in the repository is copy-pasta from a prior framework.

**Comment by HFauto** [comment]
Hello, is there a simple version of this Arduino library or a version of Stm32?

**Comment by jspark311** [comment]
I am closing this issue as "WON'T FIX". The synchronous Arduino library will never be written. If this driver is ever ported, it will be under an async abstraction framework that most Arduino users would consider too complicated. If that driver is ever ported, it will end up here:
https://github.com/jspark311/ManuvrDrivers

This excerpt from that repo's README summarizes my reasoning:
> If you are using any of my atomized Arduino libraries for specific drivers, you might have namespace conflicts. [...] My advice would be to abandon those synchronous drivers, and re-work your sketch to use the async version. The synchronous versions of these libraries were written more as demonstration pieces, and aren't maintained unless a major bug is found. Their async counterparts in this repo are much better by all standards except simplicity.

I have only left the remains of the prior driver as possible guide-posts for anyone who might otherwise be trying to write one from nothing.
